### ISSUE TITLE
Comments don't appear to grey out completely inside cfquery

### ISSUE THREAD

**Issue by ghedwards** [jcberquist/sublimetext-lucee#10]
Comments don't appear to grey out completely inside cfquery

cfquery ...
<img width="803" alt="screen shot 2015-11-18 at 11 52 51 am" src="https://cloud.githubusercontent.com/assets/125586/11230505/0560707e-8deb-11e5-8f8a-32b4b073904b.png">
/cfquery

**Comment by jcberquist** [comment]
Thanks for reporting this.
