### ISSUE TITLE
No HTML color coding inside cfsavecontent

### ISSUE THREAD

**Issue by KrunchMuffin** [jcberquist/sublimetext-lucee#12]
I don't know if this is by design or a bug. I would expect the HTML to be colored.

![image](https://cloud.githubusercontent.com/assets/1037197/11508348/5191fcde-9826-11e5-8bbc-eced644f8470.png)

**Comment by jcberquist** [comment]
It should be colored. I suspect something above the code you posted has goofed the parser. Is it possible for you to post more of the context, or try narrowing it down yourself and see when the highlighting breaks?

**Comment by KrunchMuffin** [comment]
sure, I'll see  what I can do.

**Comment by KrunchMuffin** [comment]
I broke it down to just this and it still does it.

    <cfcomponent displayname="Customer" hint="Customer methods" output="false">

        <cffunction>
            <cfsavecontent variable="data">
            <div class="row">
                <div class="col-sm-12 col-lg-6 toppad">
                    <div class="panel panel-default">
                        <div class="panel-heading">

                        </div>

            </cfsavecontent>

            <cfreturn data>
        </cffunction>

    </cfcomponent>

**Comment by jcberquist** [comment]
Perfect, thanks :+1: . I should have a fix for this soon. I don't currently have any html matching set up for text inside of functions, hence the lack of color.

**Comment by KrunchMuffin** [comment]
Working great. thanks!

**Comment by jcberquist** [comment]
Great! Thanks for confirming that it works.
