### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by cybersonic** [jcberquist/sublimetext-lucee#14]
Hi there, I followed the guide to installing the package, but when I re-start Sublime Text 3 (build 3083) I don't have any CFML syntax in the language and .cfc files (for example) open as Plain Text and there is no Lucee syntax in the drop down, see 
<img width="305" alt="screen shot 2016-01-05 at 11 12 30" src="https://cloud.githubusercontent.com/assets/148252/12113819/3dfa6d36-b39d-11e5-8da8-d88d6c3ad608.png">

**Comment by cybersonic** [comment]
I realised I wasn't on the dev version of Sublime (I should have RTFM!) 
Closing this ticket.

**Comment by jcberquist** [comment]
Hi Mark, if you are looking for CFML syntax highlighting I have it working on build 3083 here: https://github.com/jcberquist/sublimetext-cfml 
I don't have syntax highlighting for .lucee files that works on 3083 yet though.

**Comment by cybersonic** [comment]
Thanks for that, I just upgraded Sublime to 3095 and things seem to be working well! Looks good!
