### ISSUE TITLE
cfc completion

### ISSUE THREAD

**Issue by maverck** [jcberquist/sublimetext-lucee#17]
Hi,

Thanks a lot for making this. It's a great improvement over the original CFML addon for sublime text.  
I have gotten an error when setting up model completions however.
I have a rather large CFC repository and your completion seems to crash as it scans this folder. It works great if i limit it to certain sub folders.

I suspect it's having problems scanning one of my CFCs but im not sure which and the console output doesn't indicate which either.  

Here is the console output.

Traceback (most recent call last):
  File "C:\Users\MAV\AppData\Roaming\Sublime Text 3\Packages\sublimetext-lucee-master\src\modelcompletions\projectcompletions.py", line 62, in load_project
    beans, count = load_directory(path)
  File "C:\Users\MAV\AppData\Roaming\Sublime Text 3\Packages\sublimetext-lucee-master\src\modelcompletions\componentfinder.py", line 37, in load_directory
    beans.update(load_file(full_file_path, bean_names))
  File "C:\Users\MAV\AppData\Roaming\Sublime Text 3\Packages\sublimetext-lucee-master\src\modelcompletions\componentfinder.py", line 47, in load_file
    functions = find_functions(file_string)
  File "C:\Users\MAV\AppData\Roaming\Sublime Text 3\Packages\sublimetext-lucee-master\src\modelcompletions\functionfinder.py", line 48, in find_functions
    functions.extend([function_tuple for function_tuple in find_tag_functions(file_string) if function_tuple[0] != "init"])
  File "C:\Users\MAV\AppData\Roaming\Sublime Text 3\Packages\sublimetext-lucee-master\src\modelcompletions\functionfinder.py", line 48, in <listcomp>
    functions.extend([function_tuple for function_tuple in find_tag_functions(file_string) if function_tuple[0] != "init"])
TypeError: 'NoneType' object is not subscriptable

**Comment by maverck** [comment]
Also as a side request would it be possible to setup prefix/suffixs on the completions in the project file.  
for example i like to add the Obj suffix to objects when i create them as an easy identifier. for example
order.cfc would be set as OrderObj but this means i would not be able to use your completion script.

**Comment by jcberquist** [comment]
With regard to the issue you are having, based on the trace, it looks to me like you might have a tag function that either does not have a name attribute, or is not being found by the regex I use. I will push an update that will print the function string when it can't find a name, and prevents the error from halting the indexing.

**Comment by jcberquist** [comment]
Regarding your second comment, could you say more about your use case? You mention creating objects, do you mean, for example: `orderObj = new order()`? Or possibly you are using `createObject()`? Either way, I assume you are creating an instance of a cfc, and then you would like the completions for that cfc to be shown, even when the variable name does not match the cfc name. If I am understanding you correctly, that is definitely a use case I am interesting in supporting, and it would be helpful to me to know more about how you are instantiating your cfcs.

**Comment by maverck** [comment]
yes you are correct in your assumption. 

if i have an order.cfc i generally go orderObj = createObject(...).init()

Thanks.

**Comment by jcberquist** [comment]
Sorry about the delay, I do have some ideas about your desired use case of allowing for a suffix to be appended to your cfc objects, but I haven't gotten to it yet. Were you able to sort out why you were getting the error you mentioned in your original comment?

Also, unless you are using the Lucee specific (`.lucee`) dialect, I recommend you switch to the https://github.com/jcberquist/sublimetext-cfml package. That one can be installed via Package Control. I am waiting for Lucee 5 to be released and the Lucee dialect to be finalized before I go forward here.

**Comment by maverck** [comment]
The delay is fine, I did also notice the cfml package and will use that in the future.  
I was also able to find my problem yes thanks to your change.  
I simply had a code snippet in there somewhere with a note in it relating to coldfusion builder. obviously something from a very very long time ago, no idea why it was there but that was the issue. i had $$(FunctionName) or whatever the syntax is for snippet parameters and your script found this very confusing. I simply deleted it and it's working perfectly now.

As a very low priority the only other thing i've noticed is if i have two CFCs with the same name i'm not sure how it works out which functions to provide hints for. I haven't experimented with it much however

**Comment by jcberquist** [comment]
Thanks for letting me know, glad you figured it out. The indexing is done via regex, so I am not surprised that there could be false positives.

Also right now the model folder indexing takes the approach that last file indexed wins, so to speak. It is set up to work with DI/1 where cfcs are registered with their containing folder as part of the bean name, so name collisions would be less likely. I am hoping to make it more robust for situations where the cfc can be determined via the dotted path used to create it, though this will probably be limited to a single file at a time.

**Comment by jcberquist** [comment]
In the cfml plugin I just added the ability to define prefixes and suffixes for the cfc completions in a project. Could you take a look and see if it works for your use case mentioned above?

**Comment by maverck** [comment]
It has been working for me yes thank you. Sorry it took so long to reply.
