### ISSUE TITLE
Atom port

### ISSUE THREAD

**Issue by KrunchMuffin** [jcberquist/sublimetext-lucee#18]
Is there a way to get this ported to Atom?

**Comment by jcberquist** [comment]
I am sure you saw that a port of the syntax highlighting was integrated into the [atom-language-cfml](https://github.com/atuttle/atom-language-cfml) Atom package. That is probably the part that is easiest to move over, but even there there isn't a straight one to one correspondence. I worked on it, and @elpete put in quite a bit of work on it as well. As for the rest of the package, it would take some effort. The Atom API is very nice from what I have seen, but Atom uses JavaScript/CoffeeScript and ST uses Python for plugins, and their API's are obviously going to be different. So porting is not straightforward. It would take time that I don't have. But I don't mind anyone else having a go at it :smiley:
