### ISSUE TITLE
attributes without quotes throw off the syntax highlighting in a script cfc

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-lucee#2]
`property name="test" required=true` vs `property name="test" required="true"` The former results in syntax highlight errors.

**Comment by jcberquist** [comment]
Is `required=true` followed by a `;`, because I do see that breaking the syntax.

**Comment by jcberquist** [comment]
I fixed the `;` issue, but I will wait to close this to see if that is actually fixes the errors you are seeing.

**Comment by mjhagen** [comment]
Yes, that fixed it!
