### ISSUE TITLE
Tag property content assist

### ISSUE THREAD

**Issue by ghedwards** [jcberquist/sublimetext-lucee#9]
Where applicable the tag property assist does not provide properties with available options.

i.e. <cffunction access="public|private" .. I think the sublime coldFusion plugin simply provides pre-filled properties as options in the available properties. eg. access="", access="public", access="private"

Thanks for all your hard work, I've started using this again in my day to day work.

**Comment by jcberquist** [comment]
I put some thought into this a while back. My preference was not to add multiple options to select from for each tag attribute, but rather to provide a separate set of attribute value completions for each attribute after the attribute was inserted. Either way it will take a bit of work to get the possible attribute values all entered. (Though I might be able to do it more easily by making use of cfdocs.org data.)

I do agree that this would be nice to have and I will try to get to it at some point.

**Comment by ghedwards** [comment]
Is this easy to do, is it simply a matter of modifying a config file somewhere? If so perhaps it's something that can be done bit by bit on commonly used tags. ie. cffunction, cfargument, cfquery ?

**Comment by jcberquist** [comment]
I pushed an update to add tag attribute value completions, pulling the data from http://cfdocs.org. Let me know how it works.
